language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
before_install:
    - pip install --upgrade pip
install:
    - make build
    - pip install -r test_requirments.txt
    - pip install codecov
script:
    - pytest -v tests/ --cov-report html
after_success:
    - codecov
