language: python
dist: xenial
python:
    - "3.7"
    - "3.6"
sudo: required
before_install:
    - pip install --upgrade pip
install:
    - make build
    - pip install -r test_requirements.txt
    - pip install codecov
script:
    - pytest -v tests/ --cov-report html
after_success:
    - codecov
