openapi: 3.0.2

info:
  title: sdx-validate
  description: A service for validating survey responses.
  version: "2.17.0"

servers:
  - url: http://localhost:8082/

paths:
  /healthcheck:
    get:
      summary: Healthcheck.
      description: Simple endpoint that reports the health of the application.
      responses:
        200:
          description: Healthcheck retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        500:
          $ref: '#/components/responses/ServerError'
  /info:
    $ref: '#/paths/~1healthcheck'

  /validate:
    post:
      summary: Validate
      description: Validates the survey response
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Valid'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

components:
  responses:
    Valid:
      description: Passed validation
      content:
        application/json:
          schema:
            type: object
            properties:
              valid:
                type: boolean
                example: true
    ClientError:
      description: Client error - failed validation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              message:
                type: string
                example: "'type'"
              uri:
                type: string
                example: "http://localhost:8082/validate"
              valid:
                type: boolean
                example: false
    ServerError:
      description: Server error.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
                example: "Internal server error ..."
  requestBodies:
    SurveyResponse:
      description: survey response
      content:
        application/json:
          schema:
            type: object
            properties:
              type:
                type: string
                example: "uk.gov.ons.edc.eq:surveyresponse"
              origin:
                type: string
                example: "uk.gov.ons.edc.eq"
              survey_id:
                type: string
                example: "023"
              version:
                type: string
                example: "0.0.1"
              collection:
                type: object
                properties:
                  exercise_sid:
                    type: string
                    example: "hfjdskf"
                  instrument_id:
                    type: string
                    example: "0203"
                  period:
                    type: string
                    example: "0216"
              submitted_at:
                type: string
                example: "2016-03-12T10:39:40Z"
              metadata:
                type: object
                properties:
                  user_id:
                    type: string
                    example: "789473423"
                  ru_ref:
                    type: string
                    example: "12345678901A"
              data:
                type: object
                example: '"11": "01/04/2016",
                            "12": "31/10/2016",
                            "20": "1800000",
                            "51": "84",
                            "146": "some comment"'
