name: Build

on: [push]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install packages
      run: pip install --upgrade pip
    - name: make build
      run: |
        make build
        pip install -r test_requirements.txt
        pip install codecov
    - name: run tests
      run: pytest -v tests/ --cov-report html
    - name: get coverage
      run: codecov


